### PR TITLE
15 as a registered owner i can delete a customer

### LINKED ISSUE #15: As a registered owner, I can delete a customer
So that I can remove redundant or incorrect customer records, especially when unforeseen errors occur.

### PR DESCRIPTION
**Pull request by jianyangg**
Close #15, updated delete command to align with UG

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java [hunk 1]
```diff
@@ -36,13 +37,23 @@ public CommandResult execute(Model model) throws CommandException {
...
-            throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+        // Instead of the above, loop through the list, and check if the customer ID matches
+        boolean found = false;
+        Customer customerToDelete = null;
+        for (Customer customer : lastShownList) {
+            if (customer.getCustomerId() == targetIndex.getOneBased()) {
+                found = true;
+                customerToDelete = customer;
+                break;
+            }
```
Comment (zhonghan721) [inline src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java:48]: Nice!

File: src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java [hunk 2]
```diff
@@ -36,13 +37,23 @@ public CommandResult execute(Model model) throws CommandException {
...
         }
 
-        Customer customerToDelete = lastShownList.get(targetIndex.getZeroBased());
-        model.deletePerson(customerToDelete);
-        return new CommandResult(String.format(MESSAGE_DELETE_PERSON_SUCCESS, Messages.format(customerToDelete)));
+        if (found && customerToDelete != null) {
```
Comment (zhonghan721) [inline src/main/java/seedu/address/logic/commands/customer/CustomerDeleteCommand.java:51]: Hmm, would `found` alone be a sufficient check here?

**Review by zhonghan721 — APPROVED** [review]
LGTM!
