### PR TITLE
Fix UI list refreshing bug

### LINKED ISSUE #142: Fix UI list refreshing bug

### PR DESCRIPTION
**Pull request by zhonghan721**
Closes #142 

Fix UI list refreshing bug
Block delivery `add` and `delete` command from executing while logged out
Add tests for user `login` and `logout`

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java [hunk 1]
```diff
@@ -97,6 +97,21 @@ public void execute_invalidDeliveryDate_throwsCommandException() {
                 deliveryAddCommand.execute(modelStub));
     }
 
+    @Test
+    public void execute_deliveryAcceptedByModelLoggedOut_addFailure() {
```
Comment (jianyangg) [inline src/test/java/seedu/address/logic/commands/DeliveryAddCommandTest.java:101]: The naming for this test case could be clearer. 
Perhaps `execute_addDeliveryWhenLoggedOut_exceptionThrown` ?

**Review by jianyangg — APPROVED** [review]
LGTM! Good job fixing the UI bug.
