### PR TITLE
Fix no delivery

### LINKED ISSUE #236: Delivery List does not work without arguments
`delivery list` command does not work without the optional arguments

### PR DESCRIPTION
**Pull request by juliusgambe**
Fix no delivery list when no arguments

### CODE REVIEW

**Comment by B-enguin** [comment]
Closes #236

File: src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java [hunk 1]
```diff
@@ -59,9 +58,8 @@ public void parse_invalidArgs_throwsParseException() {
 
     @Test
     public void parse_emptyArgs_throwsParseException() {
```
Comment (jianyangg) [inline src/test/java/seedu/address/logic/parser/delivery/DeliveryListParserTest.java]: If it's parse success, should we update the naming of the test case as well?

**Review by jianyangg — APPROVED** [review]
Just need to fix the naming of the function. LGTM otherwise!
