### PR TITLE
Fix typo in delivery notes error message

### LINKED ISSUE #388: [PE-D][Tester A] Minor typo in error message for editing deliveries
Just a minor typo in the error message below when adding a note to a delivery, perhaps you had meant to leave the word "not" out?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Chandan8186/ped#2

### PR DESCRIPTION
**Pull request by zhonghan721**
Closes #388

### CODE REVIEW

File: src/main/java/seedu/address/model/delivery/Note.java [hunk 1]
```diff
@@ -9,7 +9,7 @@
 public class Note {
 
     public static final String MESSAGE_CONSTRAINTS =
-        "Note should not be a non-empty alphanumeric string";
+        "Note should be a non-empty alphanumeric string";
```
Comment (jianyangg) [inline src/main/java/seedu/address/model/delivery/Note.java:12]: Since this error message is for the user, should we avoid in using "string" and align with our User Guide in saying "The note must consist of alphanumeric characters and cannot be empty."?

**Review by jianyangg — APPROVED** [review]
Just one comment, but LGTM otherwise.
