### PR TITLE
Fix Bug - Delivery details not updated

### LINKED ISSUE #481: Bug - Delivery address not updated
After performing `customer edit` on address, `delivery` address is not updated

### PR DESCRIPTION
**Pull request by zhonghan721**
Delivery details associated with edited customer are not updated automatically

### CODE REVIEW

**Comment by jianyangg** [comment]
Close #481

File: src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java [hunk 1]
```diff
@@ -125,6 +137,51 @@ private static Customer createEditedCustomer(Customer customerToEdit,
                 updatedEmail, updatedAddress);
     }
 
+    /**
+     * Updates all the deliveries associated with the customer with new customer details.
+     */
+    protected static void updateDelivery(Model model, Customer editedCustomer) {
```
Comment (juliusgambe) [inline src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java:142]: Is there are a reason why this is `protected` ?

File: src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java [hunk 2]
```diff
@@ -100,7 +108,11 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_PERSON);
         } else {
             model.setCustomer(customerToEdit, editedCustomer);
+
+            // update delivery associated with the edited customer
+            updateDelivery(model, editedCustomer);
             model.updateFilteredCustomerList(PREDICATE_SHOW_ALL_CUSTOMERS);
```
Comment (juliusgambe) [inline src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java]: May want to merge master into current branch to show all filtered customer list.

File: src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java [hunk 3]
```diff
@@ -125,6 +137,51 @@ private static Customer createEditedCustomer(Customer customerToEdit,
...
+
+        OrderDate orderDate = deliveryToEdit.getOrderDate();
+
+        DeliveryDate updatedDeliveryDate =
+                deliveryEditDescriptor.getDeliveryDate().orElse(deliveryToEdit.getDeliveryDate());
+
+        DeliveryStatus updatedDeliveryStatus =
+                deliveryEditDescriptor.getStatus().orElse(deliveryToEdit.getStatus());
+
+        Note updatedNote = deliveryEditDescriptor.getNote().orElse(deliveryToEdit.getNote());
```
Comment (juliusgambe) [inline src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java]: Actually would `deliveryEditDescriptor` be empty in this case since `descriptor` is a brand new `DeliveryEditDescriptor` so we can just directly set the variable? etc. 
`DeliveryName updatedDeliveryName = deliveryToEdit.getName()`

**Review by juliusgambe — COMMENTED** [review]
Some general comments

File: src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java (hunk 1 above)
Comment (zhonghan721) [reply src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java:142]: This method is used by `CustomerEditCommandTest` to update the deliveries in the expected model

Comment (zhonghan721) [reply src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java:142]: This method is used by `CustomerEditCommandTest` to update the deliveries in the expected model

File: src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java (hunk 3 above)
Comment (zhonghan721) [reply src/main/java/seedu/address/logic/commands/customer/CustomerEditCommand.java]: Good catch, have updated it accordingly

**Review by juliusgambe — APPROVED** [review]
Thanks. LGTM
