### PR TITLE
244 bug delivery list today

### LINKED ISSUE #48: As an owner, I can see the list of deliveries that would be
...delivered for the day so that I can prioritise particular orders.

### PR DESCRIPTION
**Pull request by juliusgambe**

### CODE REVIEW

File: src/main/java/seedu/address/model/delivery/Date.java [hunk 1]
```diff
@@ -10,8 +10,9 @@
  * Represents a Date in the address book.
  */
 public class Date implements Comparable<Date> {
+    public static final String FORMAT = "yyyy-MM-dd";
```
Comment (jianyangg) [inline src/main/java/seedu/address/model/delivery/Date.java:13]: If we're using this form of capitalisation, we may have to update UG (feature) and DG (use cases).

**Review by jianyangg — APPROVED** [review]
Some general comments, otherwise LGTM

File: src/main/java/seedu/address/model/delivery/Date.java (hunk 1 above)
Comment (juliusgambe) [reply src/main/java/seedu/address/model/delivery/Date.java:13]: Resolved. I replaced the UG but DG don't have when I try to find.
